# Generated by Django 5.2.8 on 2025-11-23 11:46

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CSVUpload",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("original_filename", models.CharField(max_length=255)),
                ("file", models.FileField(upload_to="csv_uploads/")),
                ("total_rows", models.BigIntegerField(default=0)),
                ("processed_rows", models.BigIntegerField(default=0)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("errors", models.JSONField(blank=True, default=list)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "csv_uploads",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CSVData",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("row_number", models.BigIntegerField(db_index=True)),
                ("data", models.JSONField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "upload",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="csv_processor.csvupload",
                    ),
                ),
            ],
            options={
                "db_table": "csv_data",
            },
        ),
        migrations.AddIndex(
            model_name="csvupload",
            index=models.Index(
                fields=["user", "created_at"], name="csv_uploads_user_id_44e099_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="csvupload",
            index=models.Index(
                fields=["status", "created_at"], name="csv_uploads_status_128435_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="csvdata",
            index=models.Index(
                fields=["upload", "row_number"], name="csv_data_upload__67e2c8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="csvdata",
            index=models.Index(fields=["upload"], name="csv_data_upload__7934df_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="csvdata",
            unique_together={("upload", "row_number")},
        ),
    ]
