# Generated by Django 5.2.8 on 2025-11-23 18:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("csv_processor", "0001_initial"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="csvdata",
            name="csv_data_upload__67e2c8_idx",
        ),
        migrations.AlterUniqueTogether(
            name="csvdata",
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name="csvdata",
            name="row_number",
        ),
    ]
